DROP DATABASE IF EXISTS INTEGRADORA_BIEN;
CREATE DATABASE IF NOT EXISTS INTEGRADORA_BIEN;
USE INTEGRADORA_BIEN;
SELECT DATABASE();

DROP TABLE IF EXISTS MEDICAMENTOS;
CREATE TABLE IF NOT EXISTS MEDICAMENTOS(
CVE_MEDICAMENTO       INT(4)          AUTO_INCREMENT,
NOMBRE                VARCHAR(70)     NOT NULL,
DESCRIPCION           VARCHAR(150)    NOT NULL,
STOCK                 CHAR(3)         NOT NULL,
ACTIVO                BIT(2)          NOT NULL,  
PRIMARY KEY (CVE_MEDICAMENTO)
);

DROP TABLE IF EXISTS TRATAMIENTO;
CREATE TABLE IF NOT EXISTS TRATAMIENTO(
CVE_TRATAMIENTO       INT(4)           AUTO_INCREMENT,
DESCRIPCION           VARCHAR(200)     NOT NULL,
ACTIVO                BIT(2)           NOT NULL,
CVE_MEDICAMENTO       INT(4),
PRIMARY KEY (CVE_TRATAMIENTO)
);

DROP TABLE IF EXISTS NOTA_MEDICA;
CREATE TABLE IF NOT EXISTS NOTA_MEDICA(
CVE_NOTA_MEDICA      INT(4)           AUTO_INCREMENT,
DIAGNOSTICO          VARCHAR(150)     NOT NULL,
CVE_TRATAMIENTO      INT(2),
CVE_PERSONA          INT(3),
CVE_SIGNOS           INT(3),
PRIMARY KEY (CVE_NOTA_MEDICA)
);

/*NOTA MEDICA*/
DROP TABLE IF EXISTS SIGNOS;
CREATE TABLE IF NOT EXISTS SIGNOS(
CVE_SIGNOS                INT(4)        AUTO_INCREMENT,
ESTATURA                  INT(4)        NOT NULL,
PESO                      INT(5)        NOT NULL,
FRECUENCIA_CARDIACA       VARCHAR(8)    NOT NULL,
TEMPERATURA               VARCHAR(4)    NOT NULL,
GLUCOSA                   VARCHAR(8)    NOT NULL,
TENSION_ARTERIAL          VARCHAR(9)    NOT NULL,
PRIMARY KEY (CVE_SIGNOS)
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS GINECOBSTETRICOS;
CREATE TABLE IF NOT EXISTS GINECOBSTETRICOS(
CVE_GINECOBSTETRICOS          INT(4)         AUTO_INCREMENT,
EDAD_DE_PRIMER_PERIODO        CHAR(2)        NOT NULL,
PERIODO_REGULAR               BIT(2)         NOT NULL,
DIAS_DE_DURACION              FLOAT(2)       NOT NULL,
CADA_CUANTOS_DIAS             FLOAT(2)       NOT NULL,
EMBARAZOS                     BIT(2)         NOT NULL,
CUANTAS_VECES                 FLOAT(2)       NOT NULL,
PARTO                         BIT(2)         NOT NULL,
CESAREA                       BIT(2)         NOT NULL,
ABORTO                        BIT(2)         NOT NULL,
LEGRADO                       BIT(2)         NOT NULL,
METODO_DE_PLANIFICACION       BIT(2)         NOT NULL,
CUAL_METODO                   VARCHAR(25)    NOT NULL,
PAPANICOLAO                   BIT(2)         NOT NULL,    
TIEMPO_DE_HACERLO             VARCHAR(25)    NOT NULL,
PRIMARY KEY (CVE_GINECOBSTETRICOS)     
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS HEREDOFAMILIARES;
CREATE TABLE IF NOT EXISTS HEREDOFAMILIARES(
CVE_HEREDOFAMILIARES        INT(4)         AUTO_INCREMENT,
CANCER                      BIT(2)         NOT NULL,
CONVULSIONES                BIT(2)         NOT NULL,
HIPERTENSION                BIT(2)         NOT NULL,
E_CARDICAS                  BIT(2)         NOT NULL,
E_MENTALES                  BIT(2)         NOT NULL,
DIABETES                    BIT(2)         NOT NULL,
E_ALERGICAS                 BIT(2)         NOT NULL,
TUBERCULOSIS                BIT(2)         NOT NULL,
PRIMARY KEY (CVE_HEREDOFAMILIARES) 
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS HISTORIA_CLINICA;
CREATE TABLE IF NOT EXISTS HISTORIA_CLINICA(
CVE_HISTORIA                    INT(4)       AUTO_INCREMENT,
FECHA                           DATE,
CVE_PERSONA                     INT(4),
CVE_GINECOBSTETRICOS            INT(4),
CVE_NO_PATOLOGICOS              INT(4),
CVE_QUIRURGICOS                 INT(4),
CVE_ALERGICOS                   INT(4),
CVE_TRAUMATICOS                 INT(4),
CVE_TRANSFUNCIONALES             INT(4),
CVE_ENFERMEDADES                INT(4),
CVE_CONTACTOS                   INT(4),
CVE_HEREDOFAMILIARES            INT(4),
CVE_TRATAMIENTO_HISTORIA        INT(4),
PRIMARY KEY (CVE_HISTORIA)
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS ANTECEDENTES_ALERGICOS;
CREATE TABLE IF NOT EXISTS ANTECEDENTES_ALERGICOS(
CVE_ALERGICOS          INT(4)        AUTO_INCREMENT,
ALERGIAS               BIT(2)        NOT NULL,
MEDICAMENTOS           VARCHAR(30)   NOT NULL,
PRIMARY KEY (CVE_ALERGICOS) 
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS ANTECEDENTES_TRAUMATICOS;
CREATE TABLE IF NOT EXISTS ANTECEDENTES_TRAUMATICOS(
CVE_TRAUMATICOS          INT(4)         AUTO_INCREMENT,
ACCIDENTE                BIT(2)        NOT NULL,
SECUELAS_ACCIDENTE       BIT(2)        NOT NULL,
FRACTURAS                BIT(2)        NOT NULL,
COMPLICACIONES           BIT(2)        NOT NULL,
CUAL_COMPLICACION        VARCHAR(20)   NOT NULL,
PRIMARY KEY (CVE_TRAUMATICOS) 
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS TRATAMIENTO_HISTORIA;
CREATE TABLE IF NOT EXISTS TRATAMIENTO_HISTORIA(
CVE_TRATAMIENTO_HISTORIA       INT(4)           AUTO_INCREMENT,
DESCRIPCION                    VARCHAR(200)     NOT NULL,
PRIMARY KEY (CVE_TRATAMIENTO_HISTORIA) 
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS CONTACTOS;
CREATE TABLE IF NOT EXISTS CONTACTOS(
CVE_CONTACTOS     INT(4)                AUTO_INCREMENT,
NOMBRE1            VARCHAR(70)           NOT NULL,
PARENTESCO1        VARCHAR(20)           NOT NULL,
DIRECCION1         VARCHAR(50)           NOT NULL,
TELEFONO1          CHAR(10)              NOT NULL,
NOMBRE2            VARCHAR(70)           NOT NULL,
PARENTESCO2        VARCHAR(20)           NOT NULL,
DIRECCION2         VARCHAR(50)           NOT NULL,
TELEFONO2          CHAR(10)              NOT NULL,
PRIMARY KEY (CVE_CONTACTOS)
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS ENFERMEDADES;
CREATE TABLE IF NOT EXISTS ENFERMEDADES (
CVE_ENFERMEDADES         INT(4)        AUTO_INCREMENT,
VARICELA                 BIT(2)        NOT NULL,
TOSFERINA                BIT(2)        NOT NULL,
SARAMPION                BIT(2)        NOT NULL,
RUBEOLA                  BIT(2)        NOT NULL,
SINUSITIS                BIT(2)        NOT NULL,
PAPERAS                  BIT(2)        NOT NULL,
HEPATITIS                BIT(2)        NOT NULL,
TIFOIDEA                 BIT(2)        NOT NULL,
FIEBRE_REUMATICA         BIT(2)        NOT NULL,
CONVULCIONES             BIT(2)        NOT NULL,
PARASITOS                BIT(2)        NOT NULL,
DIABETIS_MELLITUS        BIT(2)        NOT NULL,
HIPERTENSION_ARTERIAL    BIT(2)        NOT NULL,
ANEMIA                   BIT(2)        NOT NULL,
ENF_CARDIACAS            BIT(2)        NOT NULL,
ENF_RENALES              BIT(2)        NOT NULL,
TRATAMIENTO_MEDICO       BIT(2)        NOT NULL,
TIPO_TRATAMIENTO         BIT(2)        NOT NULL,
PRIMARY KEY (CVE_ENFERMEDADES)
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS ANTECEDENTES_TRANSFUNCIONALES;
CREATE TABLE IF NOT EXISTS ANTECEDENTES_TRANSFUNCIONALES (
CVE_TRANSFUNCIONALES       INT(4)        AUTO_INCREMENT,
TRANSFUNCION_SANGUINEA     BIT(2)        NOT NULL,
FECHA                      DATE          NOT NULL,
MOTIVO                     VARCHAR(25)   NOT NULL,
PRIMARY KEY (CVE_TRANSFUNCIONALES)
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS PERSONALES_NO_PATOLOGICOS;
CREATE TABLE IF NOT EXISTS PERSONALES_NO_PATOLOGICOS (
CVE_NO_PATOLOGICOS        INT(4)         AUTO_INCREMENT,
VACUNAS_RECIENTES         VARCHAR(20)    NOT NULL,
PRACTICAS_DEPORTE         BIT(2)         NOT NULL,
CUAL_DEPORTE              VARCHAR(15)    NOT NULL,
CUANTAS_VECES             CHAR(2)        NOT NULL,
FUMAS                     BIT(2)         NOT NULL,
EDAD_INICIO_F             CHAR(2)        NOT NULL,
CIGARROS_A_LA_SEMANA      CHAR(2)        NOT NULL,
BEBIDAS_ALCOHOLICAS       BIT(2)         NOT NULL,
EDAD_INICIO_A             CHAR(2)        NOT NULL,
CANTIDAD_POR_SEMANA       CHAR(2)        NOT NULL,
DROGAS                    BIT(5)         NOT NULL,
EDAD_INICIO_D             CHAR(2)        NOT NULL,
CUANTAS_VECES_D           CHAR(2)        NOT NULL, 
PRIMARY KEY (CVE_NO_PATOLOGICOS)
);

/*HISTORIA CLINICA*/
DROP TABLE IF EXISTS ANTECEDENTES_QUIRURGICOS;
CREATE TABLE IF NOT EXISTS ANTECEDENTES_QUIRURGICOS (
CVE_QUIRURGICOS           INT(4)         AUTO_INCREMENT,
OPERACION                 BIT(2)         NOT NULL,
TIPO_CIRUGIA              VARCHAR(20)    NOT NULL,
FECHA_CIRUJIA             DATE           NOT NULL,
INSTITUCION               VARCHAR(20)    NOT NULL,
PRIMARY KEY (CVE_QUIRURGICOS)
);

/*SI LLEVA INSERSION*/
DROP TABLE IF EXISTS TIPO_USUARIO;
CREATE TABLE IF NOT EXISTS TIPO_USUARIO (
CVE_TIPO_USUARIO          INT(4)          AUTO_INCREMENT,
DESCRIPCION               VARCHAR(25)     NOT NULL,
ACTIVO                    BIT(2)          NOT NULL,
PRIMARY KEY (CVE_TIPO_USUARIO)
);


/*SI LLEVA INSERSION*/
DROP TABLE IF EXISTS CARRERAS;
CREATE TABLE IF NOT EXISTS CARRERAS (
CVE_CARRERA               INT(4)          AUTO_INCREMENT,
DESCRIPCION               VARCHAR(25)     NOT NULL,
ACTIVO                    BIT(2)          NOT NULL,
PRIMARY KEY (CVE_CARRERA)
);

/*SI LLEVA INSERSION*/
DROP TABLE IF EXISTS PERIODOS;
CREATE TABLE IF NOT EXISTS PERIODOS(
CVE_PERIODO			INT(4)			AUTO_INCREMENT,
AÑO 				CHAR(5)			NOT NULL,
MES_INICIO		    VARCHAR(12) 	NOT NULL,
MES_FIN			    VARCHAR(12)		NOT NULL,
ACTIVO				BIT(2)			NOT NULL,
PRIMARY KEY (CVE_PERIODO)
);


/*DATOS PARA INGRESAR*/
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE IF NOT EXISTS USUARIO(
CVE_USUARIO			INT(4)			AUTO_INCREMENT,
CURP    			CHAR(18)		UNIQUE, /* NO VA AQUI */
PASS_TEMP			BLOB		NOT NULL,
ACTIVO				BIT(2)			NOT NULL,
CVE_PERSONA			INT(4)			NULL,
CVE_TIPO_USUARIO	INT(4)          NULL,
PRIMARY KEY (CVE_USUARIO) 
);

DROP TABLE IF EXISTS REGISTRO;
CREATE TABLE IF NOT EXISTS REGISTRO(
CVE_REGISTRO INT(4)  AUTO_INCREMENT,


);



DROP TABLE IF EXISTS GRUPOS;
CREATE TABLE IF NOT EXISTS GRUPOS(
CVE_GRUPO			INT(4)			AUTO_INCREMENT,
CVE_CARRERA			INT(4)			NOT NULL,
CVE_COORDINADOR		INT(4)			NOT NULL,
GRUPO				CHAR(4)			NOT NULL,
ACTIVO				BIT(2)			NOT NULL,
CVE_PERIODO			INT(4),
PRIMARY KEY (CVE_GRUPO)
);


DROP TABLE IF EXISTS COORDINADOR;
CREATE TABLE IF NOT EXISTS COORDINADOR(
CVE_COORDINADOR		INT(4)			AUTO_INCREMENT,
CVE_PERSONA			INT(4)  NULL,
CVE_CARRERA			INT(4)  NULL,
PRIMARY KEY (CVE_COORDINADOR)
);

DROP TABLE IF EXISTS ALUMNO;
CREATE TABLE IF NOT EXISTS ALUMNO(
CVE_ALUMNO			INT(4)			AUTO_INCREMENT,
MATRICULA			CHAR(10)		NOT NULL,
ACTIVO				BIT(2)			NOT NULL,
CVE_PERSONA			INT(4),
CVE_CARRERA			INT(4),
CVE_USUARIO			INT(4),
CVE_GRUPO 			INT(4),
PRIMARY KEY (CVE_ALUMNO)
);		


DROP TABLE IF EXISTS DATOS_PERSONA;
CREATE TABLE IF NOT EXISTS DATOS_PERSONA(
CVE_PERSONA         INT(4)          AUTO_INCREMENT,
NOMBRE              VARCHAR(25)     NOT NULL,
APE_PAT             VARCHAR(25)     NOT NULL,
APE_MAT             VARCHAR(25)     NOT NULL,
FECHA_NACIMIENTO    DATE,
GENERO              VARCHAR(18)     NOT NULL,
ESTADO           	VARCHAR(25)     NOT NULL,
CVE_CARRERA         INT(4)          NULL,
CVE_GRUPO           INT(4)          NULL,
PRIMARY KEY(CVE_PERSONA)
); 

DROP TABLE IF EXISTS EVENTOS;
CREATE TABLE IF NOT EXISTS EVENTOS(
CODIGO				INT(4)          AUTO_INCREMENT,
FECHA				DATE,
ARTICULO			VARCHAR(25)		NOT NULL,
CONTENIDO			VARCHAR(255)	NOT NULL,
TIPO				VARCHAR(25)		NOT NULL,
FOTO				lONGBLOB,
PRIMARY KEY (CODIGO) 
);

SHOW TABLES;
INSERT INTO TIPO_USUARIO(CVE_TIPO_USUARIO,DESCRIPCION,ACTIVO) VALUES
(NULL,'DOCTORA',1),
(NULL,'ALUMNO',1);

INSERT INTO PERIODOS(CVE_PERIODO,AÑO,MES_INICIO,MES_FIN,ACTIVO) VALUES
(NULL,'2019','SEPTIEMBRE','DICIEMBRE',1);



INSERT INTO CARRERAS(CVE_CARRERA,DESCRIPCION,ACTIVO) VALUES
(NULL,'TIC',1);

INSERT INTO DATOS_PERSONA(CVE_PERSONA,NOMBRE,APE_PAT,APE_MAT,FECHA_NACIMIENTO,GENERO,ESTADO,CVE_CARRERA,CVE_GRUPO)
VALUES
(NULL,'GUADALUPE','ESPINOZA','RIVEROS','2000/04/05','MUJER','HIDALGO','1','1'),
(NULL,'ANDREA SARAI','JUAREZ','MUNGUIA','2000/06/14','MUJER','HIDALGO','1','1'),
(NULL,'RIGOBERTO','GARCIA','GARCIA','2000/04/05','HOMBRE','HIDALGO','1','1');

INSERT INTO COORDINADOR(CVE_COORDINADOR,CVE_PERSONA,CVE_CARRERA) VALUES
(NULL,'3','1');


INSERT INTO GRUPOS(CVE_GRUPO,CVE_CARRERA,CVE_COORDINADOR,GRUPO,ACTIVO,CVE_PERIODO) VALUES
(NULL,'1','1','31',1,'1');

#ENCRIPTACION DE CONTRASEÑAS 

INSERT INTO USUARIO(CVE_USUARIO,CURP,PASS_TEMP,ACTIVO,CVE_PERSONA,CVE_TIPO_USUARIO) VALUES /usuario
(NULL,'EIRG000405MHGSVDA2','UTEC',1,'1','1'),
(NULL,'JUMA000614MMCRNNA4','UTEC',1,'2','2'),
(NULL,'EAND000502HHGSRGA6','UTEC',1,'3','2'); 
;

select * FROM USUARIO;

# DESINCRIPTACION

SELECT cast(uncompress(PASS_TEMP) AS CHAR) FROM USUARIO;

SELECT * FROM USUARIO;

INSERT INTO ALUMNO(CVE_ALUMNO,MATRICULA,ACTIVO,CVE_PERSONA,CVE_CARRERA,CVE_USUARIO,CVE_GRUPO) VALUES 
(NULL,'1718110388',1,'1','1','1','1'),
(NULL,'1718110394',1,'2','1','2','1'),
(NULL,'1718110384',1,'3','1','3','1');






ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_PERSONA) REFERENCES DATOS_PERSONA (CVE_PERSONA);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_GINECOBSTETRICOS) REFERENCES GINECOBSTETRICOS (CVE_GINECOBSTETRICOS);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_NO_PATOLOGICOS) REFERENCES PERSONALES_NO_PATOLOGICOS (CVE_NO_PATOLOGICOS);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_QUIRURGICOS) REFERENCES ANTECEDENTES_QUIRURGICOS (CVE_QUIRURGICOS);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_ALERGICOS) REFERENCES ANTECEDENTES_ALERGICOS (CVE_ALERGICOS);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_TRAUMATICOS) REFERENCES ANTECEDENTES_TRAUMATICOS (CVE_TRAUMATICOS);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_TRANSFUNCIONALES) REFERENCES ANTECEDENTES_TRANSFUNCIONALES (CVE_TRANSFUNCIONALES);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_ENFERMEDADES) REFERENCES ENFERMEDADES (CVE_ENFERMEDADES);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_CONTACTOS) REFERENCES CONTACTOS (CVE_CONTACTOS);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_HEREDOFAMILIARES) REFERENCES HEREDOFAMILIARES (CVE_HEREDOFAMILIARES);
ALTER TABLE HISTORIA_CLINICA ADD FOREIGN KEY (CVE_TRATAMIENTO_HISTORIA) REFERENCES TRATAMIENTO_HISTORIA (CVE_TRATAMIENTO_HISTORIA);
ALTER TABLE TRATAMIENTO ADD FOREIGN KEY (CVE_MEDICAMENTO) REFERENCES MEDICAMENTOS (CVE_MEDICAMENTO);
ALTER TABLE NOTA_MEDICA ADD FOREIGN KEY (CVE_TRATAMIENTO) REFERENCES TRATAMIENTO (CVE_TRATAMIENTO);
ALTER TABLE NOTA_MEDICA ADD FOREIGN KEY (CVE_PERSONA) REFERENCES DATOS_PERSONA (CVE_PERSONA);
ALTER TABLE NOTA_MEDICA ADD FOREIGN KEY (CVE_SIGNOS) REFERENCES SIGNOS (CVE_SIGNOS);
ALTER TABLE USUARIO ADD FOREIGN KEY (CVE_TIPO_USUARIO) REFERENCES TIPO_USUARIO (CVE_TIPO_USUARIO);
ALTER TABLE USUARIO ADD FOREIGN KEY (CVE_PERSONA) REFERENCES DATOS_PERSONA (CVE_PERSONA);
ALTER TABLE GRUPOS ADD fOREIGN KEY (CVE_CARRERA) REFERENCES CARRERAS (CVE_CARRERA);
ALTER TABLE GRUPOS ADD fOREIGN KEY (CVE_COORDINADOR) REFERENCES COORDINADOR (CVE_COORDINADOR);
ALTER TABLE GRUPOS ADD fOREIGN KEY (CVE_PERIODO) REFERENCES PERIODOS (CVE_PERIODO);
ALTER TABLE COORDINADOR ADD FOREIGN KEY (CVE_PERSONA) REFERENCES DATOS_PERSONA (CVE_PERSONA);
ALTER TABLE COORDINADOR ADD FOREIGN KEY (CVE_CARRERA) REFERENCES CARRERAS (CVE_CARRERA);
ALTER TABLE DATOS_PERSONA ADD fOREIGN KEY (CVE_CARRERA) REFERENCES CARRERAS (CVE_CARRERA);
ALTER TABLE DATOS_PERSONA ADD fOREIGN KEY (CVE_GRUPO) REFERENCES GRUPOS (CVE_GRUPO);

#CONSULTA PARA LA BUSQUEDA
CREATE VIEW ONEE AS SELECT P.CVE_PERSONA, P.NOMBRE, P.APE_PAT, P.APE_MAT, A.MATRICULA 
FROM  ALUMNO A
INNER JOIN DATOS_PERSONA P ON P.CVE_PERSONA = A.CVE_ALUMNO
WHERE A.MATRICULA LIKE '%171811%'
ORDER BY P.CVE_PERSONA ;

CREATE VIEW TWO AS SELECT DATOS_PERSONA.NOMBRE, DATOS_PERSONA.APE_PAT, DATOS_PERSONA.APE_MAT,DATOS_PERSONA.CVE_PERSONA,CVE_TIPO_USUARIO
FROM  USUARIO
INNER JOIN DATOS_PERSONA  ON DATOS_PERSONA.CVE_PERSONA = USUARIO.CVE_PERSONA;

CREATE VIEW TREE AS SELECT CVE_TIPO_USUARIO,CVE_PERSONA FROM USUARIO WHERE CURP='EAND000502HHGSRGA6' AND PASS_TEMP='UTEC';

CREATE VIEW FOUR AS SELECT DATOS_PERSONA.NOMBRE, DATOS_PERSONA.APE_PAT, DATOS_PERSONA.APE_MAT,DATOS_PERSONA.CVE_PERSONA,CVE_TIPO_USUARIO
FROM  USUARIO
INNER JOIN DATOS_PERSONA  ON DATOS_PERSONA.CVE_PERSONA = USUARIO.CVE_PERSONA WHERE DATOS_PERSONA.CVE_PERSONA = 1;
 
CREATE VIEW FIVE AS SELECT DATOS_PERSONA.NOMBRE, DATOS_PERSONA.APE_PAT, DATOS_PERSONA.APE_MAT, DATOS_PERSONA.FECHA_NACIMIENTO, DATOS_PERSONA.ESTADO, CURP
FROM  USUARIO
INNER JOIN DATOS_PERSONA  ON DATOS_PERSONA.CVE_PERSONA = USUARIO.CVE_PERSONA  WHERE DATOS_PERSONA.CVE_PERSONA = '1';

CREATE VIEW SIX AS SELECT ALUMNO.MATRICULA, USUARIO.CURP,DATOS_PERSONA.NOMBRE, DATOS_PERSONA.APE_PAT, DATOS_PERSONA.APE_MAT, DATOS_PERSONA.FECHA_NACIMIENTO, DATOS_PERSONA.ESTADO
FROM DATOS_PERSONA
INNER JOIN ALUMNO  ON ALUMNO.CVE_PERSONA = DATOS_PERSONA.CVE_PERSONA
INNER JOIN USUARIO ON USUARIO.CVE_PERSONA = DATOS_PERSONA.CVE_PERSONA;

CREATE VIEW SEVEN AS SELECT ALUMNO.MATRICULA, CARRERAS.DESCRIPCION ,DATOS_PERSONA.NOMBRE, DATOS_PERSONA.APE_PAT, DATOS_PERSONA.APE_MAT
FROM DATOS_PERSONA
INNER JOIN ALUMNO  ON ALUMNO.CVE_PERSONA = DATOS_PERSONA.CVE_PERSONA
INNER JOIN CARRERAS ON CARRERAS.CVE_CARRERA = DATOS_PERSONA.CVE_CARRERA;

CREATE VIEW OCHO AS SELECT ALUMNO.MATRICULA, CARRERAS.DESCRIPCION, GRUPOS.GRUPO,DATOS_PERSONA.NOMBRE, DATOS_PERSONA.APE_PAT, DATOS_PERSONA.APE_MAT
FROM DATOS_PERSONA
INNER JOIN ALUMNO  ON ALUMNO.CVE_PERSONA = DATOS_PERSONA.CVE_PERSONA
INNER JOIN CARRERAS ON CARRERAS.CVE_CARRERA = DATOS_PERSONA.CVE_CARRERA
INNER JOIN GRUPOS ON GRUPOS.CVE_GRUPO = DATOS_PERSONA.CVE_GRUPO;

CREATE VIEW NINE AS SELECT TIPO_USUARIO.DESCRIPCION, DATOS_PERSONA.NOMBRE, DATOS_PERSONA.APE_PAT,DATOS_PERSONA.APE_MAT, CURP FROM USUARIO
INNER JOIN TIPO_USUARIO ON TIPO_USUARIO.CVE_TIPO_USUARIO = USUARIO.CVE_TIPO_USUARIO
INNER JOIN DATOS_PERSONA ON DATOS_PERSONA.CVE_PERSONA = USUARIO.CVE_PERSONA;

CREATE VIEW TEN AS SELECT PERIODOS.AÑO,PERIODOS.MES_INICIO,PERIODOS.MES_FIN, GRUPO FROM GRUPOS
INNER JOIN PERIODOS ON PERIODOS.CVE_PERIODO = GRUPOS.CVE_PERIODO;

SELECT * FROM USUARIO;
SELECT CVE_PERSONA, CVE_TIPO_USUARIO FROM USUARIO WHERE CURP='EIRG000405MHGSVDA2' AND PASS_TEMP=compress('UTEC');
